### PR TITLE
captcha: Add automatic captcha solver

### PR DESCRIPTION
**Pull request by darktohka**
I've implemented an automatic captcha solver.

It captures and processes the captcha, turning it into a black and white image without the yellow captcha line. This postprocessed captcha is then processed using the v1 Tesseract.js engine (it is more reliable than the v2 Tesseract.js engine).

I've also cleaned up the code surrounding the automatic quiz progresser function.

There is one significant change: the sound now only plays if the OCR engine runs into an error, or ONCE when the last quiz is finished (Zafaria).

### CODE REVIEW

**Comment by akrol98** [comment]
Could you add a toggle to the settings defaulted to false and add the property to users updating, thanks.

**Comment by darktohka** [comment]
So, disable captcha solving by default?

**Comment by akrol98** [comment]
Yep, I’m typically against automatically solving captchas but since you’ve already done all the work I’m willing to include it.

**Comment by darktohka** [comment]
Captcha solving is disabled by default and can be enabled in the settings now.

**Review by akrol98 — APPROVED** [review]

**Comment by akrol98** [comment]
Thanks, I've submitted the updated extension to the Chrome Web Store and if it goes through I'll make a stickied post on the website letting people know it's now an option.

**Pull request merged**
